//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaatJaKaupungit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kaupungit
    {
        public int kaupunkiId { get; set; }
        public string kaupunginNimi { get; set; }
        public int asukasluku { get; set; }
        public int maaId { get; set; }
    
        public virtual Maat Maat { get; set; }
    }
}
